language: java
jdk: openjdk8

env:
  global:
    - secure: "Bi3ixcfdCQNHPP/GNmOpYWITbL8MK3EK+xAPe5Rl2V/RtxfrrbbveH95Cv/a4yFm0+jGlN05TdwYV4mwnYwfY0An0AjJjK3HCAwDYOcDMM7Iz4YeyilyLCXF3MTkvAye2mymjeFnc2HP4BOJjoqfqjWsQm9VLWGJFxgTOi8lFuf5KyhbPsVjEJsWl8ifRd9FwfXWgB4H1YpWF8VlsiZDDou6HTP/Y4Fd3Vdr+P8b7K03LpJ5+5L/UJIqHpJLrQJYSuf5FB4sjxqrgpmL8hjh/Ud96mCZFirzEVVSO60j55PEeOz8/BBy7Bte+SdPx0Cu0yGkIOZPAkLz/4XXx5HFeUjQ8Oa9PdfsmiOw13xDX5LUBckE9UVCYtXwexbEl9ONaEd+M8pS1s00NVUHu7UXlpzC+aq1omc5ZASDr19Hl5jUjdHPlDX3ZRREZPXJmUPz5XawuYEOoT7FBjzvvrEo74ORkRjp6x2ZVepJj7ZOXJnGSDQt9HKGpv3ysIzgjvpL3GTavpGrgBEn0DxoP2y6GmpnUxkvGr1/JBrE+Pc4kfMco49IlCWJ5Z53tF8pHspq1+Hu6MX1fL6qdWO95TeFhrDjZE6zmoMbArNeL2Uy7euGYu3QCIt0ER2BILj2tAIrKIt6o5RUAgamREXz1dNq35IEMVghpS7D8bQGPU6rsXk="

addons:
  sonarcloud:
    organization: "smart-home-oss"
    token:
      secure: $SONAR_KEY_SECURE

script:
  - ./mvnw verify sonar:sonar