version: '3'

services:
  house-manager:
    image: smart-home-oss/house-manager:latest
    container_name: house-manager-um-shoss
    build: ./
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.house.rule=Host(`house.localhost`)"
      - "traefik.http.routers.house.entrypoints=web"
    ports:
    - 7000:7000
    networks:
      - smarthomeoss

networks:
  smarthomeoss:
    external: true