version: '3'

services:
  user:
    image: smart-home-oss/house-manager:latest
    container_name: house-manager-um-shoss
    build:
      dockerfile: Dockerfile
    environment:
      OAUTH_ISSUER_URI: http://house.localhost/auth/realms/smart-home-oss
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.house.rule=Host(`house.localhost`)"
      - "traefik.http.routers.house.entrypoints=web"